name: win_amd64

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    env:
      N_AUTH_TOKEN: ${{ secrets.N_AUTH_TOKEN }}
      N_API_TOKEN: ${{ secrets.N_API_TOKEN }}
      X_PATH: ${{ secrets._x_path }}

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: luarocks/gh-actions-lua@v10
        with:
          buildCache: false
          luaVersion: "luajit-2.1"
      - uses: luarocks/gh-actions-luarocks@master

      - name: Prep luacov
        run: |
          luarocks config variables.LUA ".lua\\bin\\lua.exe"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets._x }}
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: ${{ secrets._x_path }}
          persist-credentials: false

      - name: Setup OS
        run: |
          & $env:X_PATH\scripts\windows\setup.ps1

      - name: Setup ngrok
        shell: pwsh
        run: |
          & $env:X_PATH\scripts\windows\ngrok_setup.ps1
          Start-Process PowerShell -ArgumentList '-NoExit', '-Command', '.\php-essentials\bin\ngrok\windows\ngrok.exe start --all'

      - name: Finish
        shell: pwsh
        run: |
          & $env:X_PATH\scripts\windows\timeout.ps1
